version: "3.7"

services:
  database_locars:
    image: postgres
    container_name: database_locars
    restart: always
    ports:
      - 5132:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_locars
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: locars
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
