version: "3.7"

services:
  database_locars:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_locars
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    ports:
      - 8000:3333
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local
